# CONTRACT_INVENTORY_V1
# ENDPOINT: CLI pack-check --strict
# ENDPOINT: CLI pack-check --format json
# SCHEMA: CheckDiagnostic
# SCHEMA: RunReport
# SCHEMA: BuildReceipt
# SCHEMA: OpenQId

# ============================================================================
# pack-check CLI Interface Contract
# ============================================================================
# This contract defines the CLI interface for the pack-check tool, including
# the new compliance checks (52, 53) and --strict flag behavior for REQ-001
# through REQ-005.
#
# Target: OpenAPI 3.1 style (CLI interface adaptation)
# ============================================================================

openapi: "3.1.0"
info:
  title: pack-check CLI Interface Contract
  version: "1.1.0"
  description: |
    CLI interface contract for the DemoSwarm pack-check tool.

    This contract defines:
    - CLI arguments and flags
    - Exit code semantics
    - Output formats (text and JSON)
    - Check IDs and diagnostic output
    - Constants for validation rules

# ============================================================================
# CLI Interface Definition
# ============================================================================
x-cli-interface:
  name: pack-check
  description: "Validate a DemoSwarm .claude pack for structural + contract consistency"

  arguments:
    repo_root:
      type: string
      required: false
      description: |
        Repo root directory (the directory that contains .claude/).
        If omitted, pack-check walks up from the current working directory
        until it finds a .claude/ directory.

    format:
      type: enum
      values: [text, json]
      default: text
      description: "Output format: text for human-readable, json for machine-readable"

    no_color:
      type: boolean
      default: false
      description: "Disable ANSI colors in text output"

    strict_warnings:
      type: boolean
      default: false
      description: |
        Treat warnings as errors for the process exit code.
        REQ-005: When true, exit code 1 if any warnings present.
        When false, exit code 0 even with warnings present.

  exit_codes:
    0:
      name: SUCCESS
      description: |
        All checks passed. If warnings present and --strict_warnings is false,
        still returns 0.
    1:
      name: FAILURE
      description: |
        One or more errors found, OR --strict_warnings is true and warnings present.
    2:
      name: RUNTIME_ERROR
      description: |
        pack-check itself failed (IO error, missing .claude/, etc.).
        This is a tooling/environment failure, not a validation failure.

# ============================================================================
# Check Definitions (Compliance-Related)
# ============================================================================
x-checks:
  existing:
    49:
      title: "Checking agents using demoswarm.sh have ## Skills section"
      module: drift.rs
      function: check_skills_section_required
      severity: fail
      req_trace: REQ-002
      description: |
        Validates that agent files invoking demoswarm.sh include a ## Skills
        section for discoverability. This check is already implemented.

    50:
      title: "GH body hygiene (heredoc pattern, no forbidden patterns)"
      module: drift.rs
      function: check_gh_body_hygiene
      severity: fail
      description: |
        Validates that GH posting agents use heredoc pattern for body content
        and do not contain forbidden patterns (absolute paths, temp dirs, etc.).
        This prevents Windows path failures and temp file leaks.

  new:
    52:
      title: "Checking flow commands for skill-layer boundary violations"
      module: drift.rs
      function: check_flow_boundary_enforcement
      severity: warn
      strict_severity: fail
      req_trace: REQ-001
      description: |
        Validates that flow command files (.claude/commands/flow-*.md) do not
        contain demoswarm.sh invocations or skill CLI subcommands.

        This enforces the three-tier ownership model:
        - Flow commands -> agent docs -> skill docs

        Default: warning (exit 0)
        With --strict_warnings: error (exit 1)

      scan_targets:
        - ".claude/commands/flow-*.md"

      patterns:
        demoswarm_shim:
          regex: "demoswarm\\.sh"
          message: "Flow command contains demoswarm.sh reference (skill-layer leak)"

        skill_subcommands:
          regex: "\\b(count|ms|yaml|index|receipt|receipts|openapi|line|inv|time|openq|secrets)\\b"
          message: "Flow command contains skill CLI subcommand"
          context_filter: |
            Only flag when appearing in CLI invocation context, not in prose
            describing what agents do. Implementation should check for:
            - Lines containing "bash" or "demoswarm"
            - Lines in code blocks (``` ... ```)

    53:
      title: "Checking OpenQ ID prefix patterns"
      module: drift.rs
      function: check_openq_prefix_validation
      severity: warn
      strict_severity: fail
      req_trace: REQ-003
      description: |
        Validates that OpenQ question IDs follow the canonical prefix pattern:
        OQ-<FLOW>-<NNN> where:
        - <FLOW> is one of: SIG, PLN, BLD, GAT, DEP, WIS (per openq-tools)
        - <NNN> is zero-padded three digits (001-999)

        Default: warning (exit 0)
        With --strict_warnings: error (exit 1)

      scan_targets:
        - ".runs/**/open_questions.md"

      patterns:
        canonical_qid:
          regex: "OQ-(SIG|PLN|BLD|GAT|DEP|WIS)-[0-9]{3}"
          description: "Valid QID pattern"

        invalid_flow_prefix:
          regex: "OQ-(PLAN|BUILD|SIGNAL|GATE|DEPLOY|WISDOM)-[0-9]+"
          message: "Non-canonical flow prefix (use SIG/PLN/BLD/GAT/DEP/WIS)"

        invalid_numeric_suffix:
          regex: "OQ-(SIG|PLN|BLD|GAT|DEP|WIS)-[0-9]{1,2}([^0-9]|$)"
          message: "Numeric suffix not zero-padded to three digits"

# ============================================================================
# Constants (contracts.rs additions)
# ============================================================================
x-constants:
  FLOW_CODES:
    description: |
      Canonical flow code abbreviations for OpenQ IDs.
      Source of truth: .claude/skills/openq-tools/SKILL.md
    values:
      - code: "SIG"
        flow: "signal"
        full_name: "Signal"
      - code: "PLN"
        flow: "plan"
        full_name: "Plan"
      - code: "BLD"
        flow: "build"
        full_name: "Build"
      - code: "GAT"
        flow: "gate"
        full_name: "Gate"
      - code: "DEP"
        flow: "deploy"
        full_name: "Deploy"
      - code: "WIS"
        flow: "wisdom"
        full_name: "Wisdom"

    rust_constant: |
      /// Canonical OpenQ flow codes (REQ-003, NFR-MAINT-001).
      pub const OPENQ_FLOW_CODES: &[&str] = &[
          "SIG", "PLN", "BLD", "GAT", "DEP", "WIS",
      ];

  SKILL_SUBCOMMANDS:
    description: |
      CLI subcommands for demoswarm.sh that should not appear in flow commands.
      These are skill-layer implementation details.
    values:
      - "count"
      - "ms"
      - "yaml"
      - "index"
      - "receipt"
      - "receipts"
      - "openapi"
      - "line"
      - "inv"
      - "time"
      - "openq"
      - "secrets"

    rust_constant: |
      /// Skill CLI subcommands (REQ-001, NFR-MAINT-001).
      /// These should not appear in flow commands (boundary violation).
      pub const SKILL_CLI_SUBCOMMANDS: &[&str] = &[
          "count", "ms", "yaml", "index", "receipt", "receipts",
          "openapi", "line", "inv", "time", "openq", "secrets",
      ];

# ============================================================================
# Output Schemas
# ============================================================================
components:
  schemas:
    Level:
      type: string
      enum: [pass, warn, fail]
      description: "Diagnostic severity level"

    CheckDiagnostic:
      type: object
      required:
        - level
        - check_id
        - check_title
        - message
      properties:
        level:
          $ref: "#/components/schemas/Level"
        check_id:
          type: integer
          minimum: 1
          maximum: 99
          description: "Unique check identifier"
        check_title:
          type: string
          description: "Human-readable check title"
        message:
          type: string
          description: |
            Diagnostic message. For file-location diagnostics, format:
            "<rel-path>:<line>:<content>" or "<rel-path>: <description>"

    PackCounts:
      type: object
      required:
        - agents
        - commands
        - skills
      properties:
        agents:
          type: integer
          minimum: 0
        commands:
          type: integer
          minimum: 0
        skills:
          type: integer
          minimum: 0

    RunReport:
      type: object
      description: "JSON output format for pack-check (--format json)"
      required:
        - schema_version
        - repo_root
        - errors
        - warnings
        - counts
        - diagnostics
      properties:
        schema_version:
          type: integer
          const: 1
          description: "Report schema version (bump on breaking changes)"
        repo_root:
          type: string
          description: "Absolute path to validated repo root"
        errors:
          type: integer
          minimum: 0
          description: "Count of fail-level diagnostics"
        warnings:
          type: integer
          minimum: 0
          description: "Count of warn-level diagnostics"
        counts:
          $ref: "#/components/schemas/PackCounts"
        diagnostics:
          type: array
          description: "Non-pass diagnostics only (pass filtered out)"
          items:
            $ref: "#/components/schemas/CheckDiagnostic"

    # Build Receipt Schema (for REQ-004 test fixtures)
    BuildReceipt:
      type: object
      description: |
        Build receipt JSON schema. Used by receipt-checker for validation.
        This schema defines the contract between Build flow and Gate flow.
      required:
        - run_id
        - flow
        - status
        - recommended_action
        - route_to_flow
        - route_to_agent
        - missing_required
        - blockers
        - completed_at
      properties:
        schema_version:
          type: string
          pattern: "^build_receipt_v[0-9]+$"
          description: "Schema version identifier"
        run_id:
          type: string
          minLength: 1
          description: "Run identifier"
        flow:
          type: string
          const: "build"
          description: "Must be 'build' for build receipts"
        status:
          type: string
          enum: [VERIFIED, UNVERIFIED, CANNOT_PROCEED]
          description: "Pack-standard status enum"
        recommended_action:
          type: string
          enum: [PROCEED, RERUN, BOUNCE, FIX_ENV]
          description: "Pack-standard action enum"
        route_to_flow:
          type: [integer, "null"]
          minimum: 1
          maximum: 6
          description: "Target flow (1-6) or null"
        route_to_agent:
          type: [string, "null"]
          description: "Target agent name or null"
        missing_required:
          type: array
          items:
            type: string
          description: "List of missing required inputs"
        blockers:
          type: array
          items:
            type: string
          description: "List of blockers preventing VERIFIED status"
        concerns:
          type: array
          items:
            type: string
          description: "Non-blocking concerns"
        completed_at:
          type: string
          format: date-time
          description: "ISO8601 completion timestamp"

        # Build-specific fields
        tests:
          type: object
          description: "Test execution grounding"
          required:
            - canonical_summary
            - summary_source
            - metrics_binding
          properties:
            canonical_summary:
              type: string
              description: "Pytest summary line"
            summary_source:
              type: string
              description: "Source file (e.g., build/test_execution.md)"
            metrics_binding:
              type: string
              description: "Binding identifier (e.g., test_execution:test-runner)"
            passed:
              type: integer
              minimum: 0
            failed:
              type: integer
              minimum: 0
            skipped:
              type: integer
              minimum: 0
            xfailed:
              type: integer
              minimum: 0
            xpassed:
              type: integer
              minimum: 0

        critic_verdicts:
          type: object
          description: "Critic agent verdicts"
          properties:
            test_critic:
              type: [string, "null"]
              enum: [VERIFIED, UNVERIFIED, CANNOT_PROCEED, null]
            code_critic:
              type: [string, "null"]
              enum: [VERIFIED, UNVERIFIED, CANNOT_PROCEED, null]

        counts:
          type: object
          description: "Mechanical counts"
          properties:
            impl_files_changed:
              type: integer
              minimum: 0
            test_files_changed:
              type: integer
              minimum: 0
            doc_files_changed:
              type: integer
              minimum: 0
            total_lines_added:
              type: integer
              minimum: 0
            total_lines_removed:
              type: integer
              minimum: 0

    # OpenQ ID Schema
    OpenQId:
      type: string
      pattern: "^OQ-(SIG|PLN|BLD|GAT|DEP|WIS)-[0-9]{3}$"
      description: |
        Canonical Open Question ID format.
        - Prefix: OQ-
        - Flow code: SIG, PLN, BLD, GAT, DEP, WIS
        - Numeric suffix: 001-999 (zero-padded)
      examples:
        - "OQ-SIG-001"
        - "OQ-PLN-004"
        - "OQ-BLD-012"

# ============================================================================
# Error Model
# ============================================================================
x-error-model:
  description: |
    pack-check uses a consistent error model for all diagnostics.

    Text output format:
      <symbol> <message>

    Where <symbol> is:
      - Green checkmark for pass
      - Yellow warning for warn
      - Red X for fail

    For file-location errors, message format:
      <rel-path>:<line>:<content>

    JSON output provides structured diagnostics with check_id, level, and message.

  diagnostic_format:
    text:
      pass: "{green checkmark} {message}"
      warn: "{yellow warning} {message}"
      fail: "{red x} {message}"

    file_location: "{rel_path}:{line_number}:{line_content}"

# ============================================================================
# Traceability
# ============================================================================
x-traceability:
  REQ-001:
    check_id: 52
    description: "Flow boundary enforcement"
    validation_points:
      - "demoswarm.sh reference in flow-*.md"
      - "Skill subcommand in flow-*.md"

  REQ-002:
    check_id: 49
    description: "Skills section enforcement (existing)"
    validation_points:
      - "Agent contains demoswarm.sh but lacks ## Skills"

  REQ-003:
    check_id: 53
    description: "OpenQ prefix validation"
    validation_points:
      - "QID uses non-canonical flow code"
      - "QID numeric suffix not zero-padded"

  REQ-004:
    description: "Build-to-Gate handshake test fixtures"
    validation_points:
      - "build_receipt_valid.json passes schema validation"
      - "build_receipt_invalid.json fails with expected error"

  REQ-005:
    cli_flag: "--strict_warnings"
    description: "Warning-first validation mode"
    validation_points:
      - "Without --strict: exit 0 even with warnings"
      - "With --strict: exit 1 when warnings present"

  NFR-MAINT-001:
    constants:
      - "OPENQ_FLOW_CODES in contracts.rs"
      - "SKILL_CLI_SUBCOMMANDS in contracts.rs"
